import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-16 lg:px-8">
      <h1 className="text-2xl font-bold tracking-tight mb-6 sm:text-3xl sm:mb-8">
        Terms of Service
      </h1>

      <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground">
        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Acceptance of Terms
          </h2>
          <p>
            By using Bloodwork Online, you agree to these terms. If you do not agree,
            please do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Medical Disclaimer
          </h2>
          <p>
            <strong>
              Bloodwork Online is NOT a medical service and does NOT provide medical
              advice, diagnosis, or treatment.
            </strong>{" "}
            The explanations provided are for informational and educational
            purposes only. They are generated by artificial intelligence and may
            contain errors or inaccuracies.
          </p>
          <p>
            Always consult a qualified healthcare provider for medical advice.
            Never disregard professional medical advice or delay seeking it
            because of information provided by this service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Service Description
          </h2>
          <p>
            Bloodwork Online uses AI technology to provide educational explanations
            of blood test markers. The service processes data you provide (blood
            test values, age, gender) and returns AI-generated interpretations.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Payments and Refunds
          </h2>
          <p>
            Paid features are available through one-time purchases or
            subscriptions. Subscriptions can be cancelled at any time. Refund
            requests are handled on a case-by-case basis. Contact us if you
            believe you are entitled to a refund.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Limitation of Liability
          </h2>
          <p>
            Bloodwork Online is provided &quot;as is&quot; without warranties of any
            kind. We are not liable for any damages arising from your use of the
            service, including but not limited to health decisions made based on
            AI-generated explanations.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">
            Acceptable Use
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Use the service for any purpose other than personal blood test
              interpretation
            </li>
            <li>Attempt to bypass rate limits or usage restrictions</li>
            <li>Use automated tools to access the service at scale</li>
            <li>Resell or redistribute the analysis results commercially</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Changes</h2>
          <p>
            We may update these terms at any time. Continued use of the service
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <p className="text-xs text-muted-foreground/60 pt-4">
          Last updated: April 2026
        </p>
      </div>
    </div>
  );
}
